Vagrant.configure("2") do |config|

	config.vm.box = "bento/ubuntu-24.04"

	#port forwarding
	config.vm.network "forwarded_port", 
		guest: 80,			#porta di apache dentro ubuntu 
		host: 8080			#porta del mac

	#shell provisioning
	config.vm.provision "shell", 
		path: "setup.sh"

end
