apiVersion: v1
data:
  password: MDAwMA==
  username: dmFsZXJpbw==
kind: Secret
metadata:
  creationTimestamp: "2026-07-09T08:48:25Z"
  name: user-pass
  namespace: default
  resourceVersion: "305914"
  uid: ea8a1df6-d297-4f8b-93b2-a85fd30cc292
type: Opaque
