FROM ubuntu:22.04
#l'immagine parte da ubuntu

RUN mkdir /game
#si crea la cartella /game

RUN touch /game/state.txt
#si crea il file di stato locale

CMD ["sleep", "infinity"]
#il container resta attivo
