Vagrant.configure("2") do |config|


  config.vm.define "db-source" do |db|

    db.vm.box = "generic/rocky9"
    db.vm.hostname = "db-source"

    db.vm.network "private_network",
      ip: "192.168.56.10"


    db.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 1
    end


    db.vm.provision "shell",
      path: "scripts/prepare-ansible.sh"

  end



  config.vm.define "db-destination" do |db|

    db.vm.box = "generic/rocky9"
    db.vm.hostname = "db-destination"

    db.vm.network "private_network",
      ip: "192.168.56.11"


    db.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 1
    end


    db.vm.provision "shell",
      path: "scripts/prepare-ansible.sh"

  end


end